name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-dependencies:
    name: Check for Updates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated packages
        run: |
          echo "Checking for outdated packages..."
          npm outdated || echo "All packages are up to date"

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Create issue for manual review
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['dependencies']
            });

            const existingIssue = issues.find(issue => 
              issue.title.includes('Dependency Update Check')
            );

            if (!existingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Dependency Update Check - ' + new Date().toISOString().split('T')[0],
                body: `## Dependency Update Check
                
                This issue was automatically created to track dependency updates.
                
                **Last Check**: ${new Date().toISOString()}
                
                ### Next Steps:
                1. Review outdated packages: \`npm outdated\`
                2. Check for security vulnerabilities: \`npm audit\`
                3. Update packages as needed
                4. Test thoroughly after updates
                5. Close this issue when complete
                
                ### Commands to run:
                \`\`\`bash
                # Check outdated packages
                npm outdated
                
                # Check security
                npm audit
                
                # Update packages (be careful!)
                npm update
                
                # Run tests after updates
                npm test
                \`\`\``,
                labels: ['dependencies', 'automated']
              });
            }
